/// THIS FILE IS AUTOGENERATED. DO NOT MODIFY
use lazy_static::lazy_static;
use std::collections::BTreeMap;

lazy_static! {
    pub static ref IMAGE_MAP: BTreeMap<(u32, u32, u32), &'static str> = {
        let mut m = BTreeMap::new();

        m
    };
}
